apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastics-pod
 #namespace: elastic
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: elasticsearch
        #image: elasticsearch:8.11.1
        image: bitnami/elasticsearch:8.11.1
        #resources:
         #   limits:
          #    cpu: 1000m
           # requests:
            #  cpu: 100m
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
            #nodeSelector:
            #name: aws-worker-1

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
    # namespace: e-search
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  #type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      name: rest
      #nodePort: 30016
    - port: 9300
      name: inter-node

---
