version: "3.9"

services:
  grafana:
    image: aniketxshinde/serversage:latest
    # image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    # volumes:
    #   - ./data/grafana/:/etc/grafana/
    environment:
      - GF_AUTH_ADMIN_USER=admin
      - GF_FEATURE_TOGGLES_ENABLE=dashgpt
      - GF_AUTH_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net

  redis:
    image: redis:7.0.15
    restart: always
    ports:
      - 6379
    deploy:
      resources:
        limits:
          memory: 200m
          cpus: "0.5"
    depends_on:
      - fluentbit
    networks:
      - monitoring-net
    logging:
      driver: fluentd 
      options:
        tag: redis.logs
        fluentd-address: localhost:24224 
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
      # - REDIS_USER=redis
      # - REDIS_PASSWORD=your_redis_password
    depends_on:
      - redis
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net


  fluentbit:
    image: fluent/fluent-bit:4.0
    container_name: fluentbit
    ports:
      - "24224:24224"
    volumes:
      - ./fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf 
    networks:
      - monitoring-net

  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    image: bitnami/elasticsearch:8.18.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "9200:9200"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
