apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: database
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        logging: "enabled,format:json" 
        # fluentbit.io/parser: "docker"  # Specify parser for Redis logs
        # Fluentd logging options can be configured via annotations or sidecar logging agents
        fluentd.io/tag: redis.logs
        fluentd.io/address: fluent-bit.monitoring.svc.cluster.local:24224
        fluentd.io/async-connect: "true"
        fluentd.io/retry-wait: 1s
        fluentd.io/max-retries: "30"
    spec:
      containers:
      - name: redis
        image: redis:7.0.15
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 200Mi
            cpu: "0.5"
          requests:
            memory: 200Mi
            cpu: "0.5"
        # If you want to configure logging drivers, usually this is done cluster-wide or via sidecar
        # Kubernetes does not support Docker logging drivers per container
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: database
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30013
