
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: monitoring
  labels:
    component: kibana
data:
  elasticsearch_username: elastic
  elasticsearch_password: bitnami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        # image: bitnami/kibana:7.17.21
        image: bitnami/kibana:8.11.1
        env:
        - name: KIBANA_ELASTICSEARCH_URL
          value: "elasticsearch.database.svc.cluster.local"
        - name: KIBANA_ELASTICSEARCH_PORT_NUMBER
          value: "9200"
        # - name: KIBANA_XPACK_SECURITY_ENCRYPTIONKEY
        #   value: "true"
        # envFrom:
        # - configMapRef:
        #     name: kibana-config
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
  labels:
    component: kibana
spec:
  type: NodePort
  selector:
    component: kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30017
---