apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush            1
        Log_Level        info
        Daemon           off
        Parsers_File     parsers.conf
        storage.type filesystem
    [INPUT]
        Name            http
        Listen          0.0.0.0
        Port            2020
    [INPUT]
        Name             forward
        Port             24224
        Listen           0.0.0.0
    [OUTPUT]
        Name             stdout
        Match            *
    [OUTPUT]
        Name             es
        Match            kubernetes.*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            kubernetes-logs
        Replace_Dots     On
        Retry_Limit      False
        Suppress_Type_Name On
    [OUTPUT]
        Name             es
        Match            etcd*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            etcd-logs
        Replace_Dots     On
        Suppress_Type_Name On
        Retry_Limit      False
    [OUTPUT]
        Name             es
        Match            postgres*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            postgres-logs
        Replace_Dots     On
        Suppress_Type_Name On
        Retry_Limit      False
    [OUTPUT]
        Name             es
        Match            keycloak*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            keycloak-logs
        Replace_Dots     On
        Suppress_Type_Name On
        Retry_Limit      False
    [OUTPUT]
        Name             es
        Match            redis*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            redis-logs
        Replace_Dots     On
        Suppress_Type_Name On
        Retry_Limit      False
    # --------------------------- Agents
    [OUTPUT]
        Name             es
        Match            pg-exporter*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            pg-exporter-logs
        Replace_Dots     On
        Suppress_Type_Name On
        Retry_Limit      False
    # --------------------------- ServerSage
    [OUTPUT]
        Name             es
        Match            grafana*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            grafana-logs
        Replace_Dots     On
        Suppress_Type_Name On
        Retry_Limit      False
    [OUTPUT]
        Name             es
        Match            oncall*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            oncall-logs
        Replace_Dots     On
        Suppress_Type_Name On
        Retry_Limit      False
    [OUTPUT]
        Name             es
        Match            celery*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            celery-logs
        Replace_Dots     On
        Suppress_Type_Name On
        Retry_Limit      False
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
