apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    k8s-app: fluent-bit
  ports:
    - name: http
      port: 2020
      targetPort: 2020
      protocol: TCP
    - name: metrics
      port: 2021
      targetPort: 2021
      protocol: TCP
    - name: forward
      port: 24224
      targetPort: 24224
      protocol: TCP
  type: ClusterIP
