version: '3.9'

networks:
  shared_network_NDML:
    external: true
services:
  tomcat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-app
    environment:
      POSTGRES_HOST_IP: postgres
      POSTGRES_PORT: "5433"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "8080:8080"
      # - "4318"


  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: otel-collector
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 100M
  #   ports:
  #     # - "4318:4318"  # OTLP http
  #     - "8889:8889"  # Prometheus metrics
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./otel-collector-config.yml:/etc/otel-collector-config.yml
  #   command: ["--config", "/etc/otel-collector-config.yml"]




