apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
  namespace: nginx
  labels:
    app: nginx-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:1.4
        args:
          - -nginx.scrape-uri=http://nginx-service.nginx.svc.cluster.local:80/nginx_status
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 9113
          name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
  namespace: nginx
  labels:
    app: nginx-prometheus-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  ports:
  - port: 9113
    targetPort: 9113
    name: metrics
  selector:
    app: nginx-prometheus-exporter