version: "3.4"

services:

  spring-boot:
    # build: ./app_springboot/
    # image: ghcr.io/blueswen/opentelemetry-apm/springboot:latest
    image: aniketxshinde/serversage:0.1.2
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - OTEL_SERVICE_NAME=spring-boot
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      # - TARGET_ONE_SVC=fastapi:8000
      # - TARGET_TWO_SVC=fastapi:8000
      # - OTEL_EXPORTER_OTLP_INSECURE=true
      # - OTEL_EXPORTER=otlp_span
      # - OTEL_METRICS_EXPORTER=none
    command: "java -javaagent:/opentelemetry-javaagent.jar -jar /app.jar"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    # image: otel/opentelemetry-collector-contrib:0.100.0
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./etc/otel-collector-config.yaml:/conf/config.yaml
    ports:
      # - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "8889:8889" # Prometheus metrics exporter
    restart: on-failure
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.7.2
    # image: grafana/tempo:2.4.1
    command: [ "--target=all", "-config.file=/etc/tempo.yaml","--auth.enabled=false" ]
    volumes:
      # - ./data/tempo:/var/tempo
      - ./etc/tempo.yaml:/etc/tempo.yaml 
    ports:
      - "3200:3200"
      - "4317:4317"  # otlp grpc


  prometheus:
    image: prom/prometheus:v2.53.4
    # image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yml:/workspace/prometheus.yml
    command:
      - --config.file=/workspace/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-admin-api
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms  
    depends_on:
      - tempo

  grafana:
    image: aniketxshinde/serversage:latest
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/dashboards:/etc/grafana/dashboards
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_FEATURE_TOGGLES_ENABLE: "timeSeriesTable"


