# -----------------------------------------------
# Persistent Volume
# -----------------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oncall-pv
  namespace: grafana
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/oncall"

---
# -----------------------------------------------
# Persistent Volume Claim
# -----------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oncall-pvc
  namespace: grafana
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: oncall-pv

---
# -----------------------------------------------
# Grafana OnCall Deployment
# -----------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-oncall
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-oncall
  template:
    metadata:
      labels:
        app: grafana-oncall
    spec:
      containers:
        - name: oncall
          image: grafana/oncall:latest
          securityContext:
            runAsUser: 1000
          command: ["sh", "-c", "uwsgi --ini uwsgi.ini"]
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_TYPE
              value: "sqlite3"
            - name: SQLITE_DB_PATH
              value: "/var/lib/oncall/oncall.db"
            - name: BROKER_TYPE
              value: "redis"
            - name: BASE_URL
              value: "http://oncall.grafana.svc.cluster.local:8080"
            - name: SECRET_KEY
              value: "my_random_secret_must_be_more_than_32_characters_long"
            - name: FEATURE_PROMETHEUS_EXPORTER_ENABLED
              value: "false"
            - name: PROMETHEUS_EXPORTER_SECRET
              value: "prometheus"
            - name: REDIS_URI
              value: "redis://redis.database.svc.cluster.local:6379/0"
            - name: DJANGO_SETTINGS_MODULE
              value: "settings.hobby"
            - name: CELERY_WORKER_QUEUE
              value: "default,critical,long,slack,telegram,webhook,retry,celery,grafana"
            - name: CELERY_WORKER_CONCURRENCY
              value: "1"
            - name: CELERY_WORKER_MAX_TASKS_PER_CHILD
              value: "100"
            - name: CELERY_WORKER_SHUTDOWN_INTERVAL
              value: "65m"
            - name: CELERY_WORKER_BEAT_ENABLED
              value: "True"
            - name: GRAFANA_API_URL
              value: "http://grafana.prometheus.svc.cluster.local:3000"
              #value: "https://uat.starmfv2.remiges.tech/tools/grafana/"
              #- name: GF_FEATURE_TOGGLES_ENABLE
              #value: "externalServiceAccounts"
          volumeMounts:
            - name: oncall-data
              mountPath: /var/lib/oncall
      volumes:
        - name: oncall-data
          persistentVolumeClaim:
            claimName: oncall-pvc
        - name: oncall-db
          emptyDir: {}
      # nodeSelector:
      #   name: aws-worker-1

---
# -----------------------------------------------
# Celery Worker Deployment
# -----------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: grafana/oncall:latest
          securityContext:
            runAsUser: 1000
          command:
            - sh
            - "-c"
            - "./celery_with_exporter.sh"
            - "ulimit -n 1048576 && celery --quiet -A engine worker --concurrency=1 --max-tasks-per-child=100 -Q default,critical,long,slack,telegram,webhook,retry,celery,grafana -l info"
          env:
            - name: DATABASE_TYPE
              value: "sqlite3"
            - name: SQLITE_DB_PATH
              value: "/var/lib/oncall/oncall.db"
            - name: BROKER_TYPE
              value: "redis"
            - name: BASE_URL
              value: "http://oncall.grafana.svc.cluster.local:8080"
            - name: SECRET_KEY
              value: "my_random_secret_must_be_more_than_32_characters_long"
            - name: FEATURE_PROMETHEUS_EXPORTER_ENABLED
              value: "false"
            - name: PROMETHEUS_EXPORTER_SECRET
              value: "prometheus"
            - name: REDIS_URI
              value: "redis://redis.database.svc.cluster.local:6379/0"
            - name: DJANGO_SETTINGS_MODULE
              value: "settings.hobby"
            - name: CELERY_WORKER_QUEUE
              value: "default,critical,long,slack,telegram,webhook,retry,celery,grafana"
            - name: CELERY_WORKER_CONCURRENCY
              value: "1"
            - name: CELERY_WORKER_MAX_TASKS_PER_CHILD
              value: "100"
            - name: CELERY_WORKER_SHUTDOWN_INTERVAL
              value: "65m"
            - name: CELERY_WORKER_BEAT_ENABLED
              value: "true"
            - name: CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP
              value: "true"
            - name: GRAFANA_API_URL
              value: "http://grafana.grafana.svc.cluster.local:3000"
              #value: "https://uat.starmfv2.remiges.tech/tools/grafana/"
              #- name: GF_FEATURE_TOGGLES_ENABLE
              #value: "externalServiceAccounts"
          volumeMounts:
            - name: oncall-data
              mountPath: /var/lib/oncall
      volumes:
        - name: oncall-data
          persistentVolumeClaim:
            claimName: oncall-pvc
        - name: oncall-db
          emptyDir: {}
      # nodeSelector:
      #   name: aws-worker-1

---
# -----------------------------------------------
# OnCall DB Migration Job
# -----------------------------------------------
apiVersion: batch/v1
kind: Job
metadata:
  name: oncall-db-migration
  namespace: grafana
spec:
  template:
    metadata:
      labels:
        app: oncall-db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: oncall-db-migration
          image: grafana/oncall:latest
          securityContext:
            runAsUser: 1000
          command: ["python", "manage.py", "migrate", "--noinput"]
          env:
            - name: DATABASE_TYPE
              value: "sqlite3"
            - name: SQLITE_DB_PATH
              value: "/var/lib/oncall/oncall.db"
            - name: BROKER_TYPE
              value: "redis"
            - name: BASE_URL
              value: "http://oncall.grafana.svc.cluster.local:8080"
            - name: SECRET_KEY
              value: "my_random_secret_must_be_more_than_32_characters_long"
            - name: FEATURE_PROMETHEUS_EXPORTER_ENABLED
              value: "false"
            - name: PROMETHEUS_EXPORTER_SECRET
              value: "prometheus"
            - name: REDIS_URI
              value: "redis://redis.database.svc.cluster.local:6379/0"
            - name: DJANGO_SETTINGS_MODULE
              value: "settings.hobby"
            - name: GRAFANA_API_URL
              value: "http://grafana.grafana.svc.cluster.local:3000"
              #value: "https://uat.starmfv2.remiges.tech/tools/grafana/"
              #- name: GF_FEATURE_TOGGLES_ENABLE
              #value: "externalServiceAccounts"
          volumeMounts:
            - name: oncall-data
              mountPath: /var/lib/oncall
      volumes:
        - name: oncall-data
          persistentVolumeClaim:
            claimName: oncall-pvc

---
# -----------------------------------------------
# OnCall Service
# -----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: oncall
  namespace: grafana
spec:
  selector:
    app: grafana-oncall
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP