apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush            1
        Log_Level        info
        Daemon           off
        Parsers_File parsers.conf
    [INPUT]
        Name             tail
        Tag              kube.*
        Multiline        On
        Parser_Firstline docker
        multiline.parser docker
        # Parser           docker
        Path             /var/log/containers/*.log
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_URL         https://kubernetes.default.svc:443
        Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix  kube.var.log.containers.
        Merge_Log        On
        Keep_Log         Off
    [OUTPUT]
        Name             es
        Match            kube.*
        Host             elasticsearch.default.svc.cluster.local
        Port             9200
        Index            kubernetes-logs
        Replace_Dots     On
        Retry_Limit      False
        Suppress_Type_Name On
        #Logstash_Prefix   kubernetes-logs
        #Logstash_Format   On
    [OUTPUT]
        Name             stdout
        Match            *

  parsers.conf: |
    [PARSER]
        Name             docker
        Format           json
        Time_Key         when
        Time_Format      %Y-%m-%dT%H:%M:%S %z
        Skip_Empty_Values true
        Types            status:integer size:integer
        Decode_Field_as   escaped_utf8 log
    

