---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: database
#   labels:
#     monitoring: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastics-pod
  namespace: database
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: elasticsearch
        image: bitnami/elasticsearch:8.11.1
        # resources:
        #   limits:
        #     cpu: 1000m
        #   requests:
        #     cpu: 100m
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: database
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      name: rest
      nodePort: 30012
    - port: 9300
      targetPort: 9300
      name: inter-node
