
receivers:
  # System metrics
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      disk: {}
      load: {}
      filesystem: {}
      memory: {}
      network: {}
      paging: {}
      processes: {}

  otlp:
    protocols:
      grpc:
      http:

  # PostgreSQL metrics
  postgresql:
    endpoint: "host.docker.internal:5432"
    username: "postgres"
    password: "postgres"
    databases:
      - "crux"  # Add other database names here if needed
    collection_interval: 10s
    tls:
      insecure: true
      insecure_skip_verify: true

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    override: false
    system:
      hostname_sources: [os]

connectors:
  spanmetrics:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  telemetry:
    metrics:
      address: localhost:8888
      level: detailed

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, debug, spanmetrics]
    metrics:
      receivers: [otlp, hostmetrics,postgresql,spanmetrics]
      processors: [resourcedetection, batch]
      exporters: [prometheus]