apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush            1
        Log_Level        info
        Daemon           off
        Parsers_File     parsers.conf
        storage.type filesystem
    # Minio Input
    [INPUT]
        Name              tail
        Tag               kube*
        Path              /var/log/containers/*.log
        Parser            docker
        Path_Key          filename
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    # Extract pod name from filename and set it as a field
    [FILTER]
        Name    lua
        Match   kube*
        Script  extract_prefix.lua
        Call    extract_prefix
    # Kubernetes Filter
    [FILTER]
        Name                kubernetes
        Match               kube*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    #------------------------------  OUTPUT  --------------------------------------------
    [OUTPUT]
        Name                es
        Match               kube*
        # Match_Regex         ^filename=minio.*$
        Host                ${elasticsearch_host}
        Port                ${elasticsearch_port}
        Index               kubernetes-logs
        Replace_Dots        On
        Generate_ID         On
        Suppress_Type_Name  On
        Include_Tag_Key     off
        Buffer_Size         1MB
        Retry_Limit         5
  parsers.conf: |
    [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S %z
        Time_Keep           On
    [PARSER]
        Name                syslog
        Format              regex
        Regex               ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key            time
        Time_Format         %b %d %H:%M:%S
  extract_prefix.lua: |
    function extract_prefix(tag, timestamp, record)
      local pod_name, namespace, fname = nil, nil, nil
      local pattern = ".*/(.-)-(.-)-(.*)_(.*)_(.*).log"
      local filename = record["filename"]
      local match = string.match(filename, pattern)
      if match then
        pod_name = match[1]
        namespace = match[4]
        fname = match[5]
      end
      if filename ~= nil then
          -- Extract prefix before first underscore
          local prefix = string.match(filename, "^([^_]+)")
          if prefix ~= nil then
              record["filename"] = fname
              record["namespace"] = namespace
              record["pod_name"] = pod_name
          end
      end
      return 1, timestamp, record
    end
