apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush            1
        Log_Level        info
        Daemon           off
        Parsers_File     parsers.conf
        storage.type filesystem
    # Redis Input
    [INPUT]
        Name              tail
        Tag               redis*
        Path              /var/log/containers/redis*.log
        Parser            docker
        Path_Key          filename
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    # Kafka Input
    [INPUT]
        Name              tail
        Tag               kafka*
        Path              /var/log/containers/kafka*.log
        Parser            docker
        Path_Key          filename
        DB                /var/log/flb_kafka.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    # Otel Input
    [INPUT]
        Name              tail
        Tag               otel*
        Path              /var/log/containers/otel*.log
        Parser            docker
        Path_Key          filename
        DB                /var/log/flb_otel.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    # Etcd Input
    [INPUT]
        Name              tail
        Tag               etcd*
        Path              /var/log/containers/etcd*.log
        Parser            docker
        Path_Key          filename
        DB                /var/log/flb_etcd.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    # Minio Input
    [INPUT]
        Name              tail
        Tag               minio*
        Path              /var/log/containers/minio*.log
        Parser            docker
        Path_Key          filename
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    # Postgres Input
    [INPUT]
        Name              tail
        Tag               postgres*
        Path              /var/log/containers/postgres*.log
        Parser            docker
        Path_Key          filename
        DB                /var/log/flb_postgres.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    # kube-proxy Input
    [INPUT]
        Name              tail
        Tag               kube-proxy*
        Path              /var/log/containers/kube-proxy*.log
        Parser            docker
        Path_Key          filename
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    # Extract pod name from filename and set it as a field
    [FILTER]
        Name    lua
        Match   *
        Script  extract_prefix.lua
        Call    extract_prefix
    # Kubernetes Filter
    [FILTER]
        Name                kubernetes
        Match               *
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    #------------------------------  OUTPUT  --------------------------------------------
    # OUTPUT for etcd logs
    [OUTPUT]
        Name                es
        Match               etcd*
        Match_Regex         ^filename=etcd.*$
        Host                ${elasticsearch_host}
        Port                ${elasticsearch_port}
        Index               etcd-logs
        Replace_Dots        On
        Generate_ID         On
        Suppress_Type_Name  On
        Include_Tag_Key     off
        Buffer_Size         1MB
        Retry_Limit         5
    # OUTPUT for kafka logs
    [OUTPUT]
        Name                es
        Match               kafka*
        Match_Regex         ^filename=kafka.*$
        Host                ${elasticsearch_host}
        Port                ${elasticsearch_port}
        Index               kafka-logs
        Replace_Dots        On
        Generate_ID         On
        Suppress_Type_Name  On
        Include_Tag_Key     off
        Buffer_Size         1MB
        Retry_Limit         5
    # OUTPUT for otel logs
    [OUTPUT]
        Name                es
        Match               otel*
        Match_Regex         ^filename=otel.*$
        Host                ${elasticsearch_host}
        Port                ${elasticsearch_port}
        Index               otel-logs
        Replace_Dots        On
        Generate_ID         On
        Suppress_Type_Name  On
        Include_Tag_Key     off
        Buffer_Size         1MB
        Retry_Limit         5
    # OUTPUT to Minio for minio logs
    [OUTPUT]
        Name                es
        Match               minio*
        Match_Regex         ^filename=minio.*$
        Host                ${elasticsearch_host}
        Port                ${elasticsearch_port}
        Index               minio-logs
        Replace_Dots        On
        Generate_ID         On
        Suppress_Type_Name  On
        Include_Tag_Key     off
        Buffer_Size         1MB
        Retry_Limit         5
    # OUTPUT to Postgres for postgres logs
    [OUTPUT]
        Name                es
        Match               postgres*
        Match_Regex         ^filename=postgres.*$
        Host                ${elasticsearch_host}
        Port                ${elasticsearch_port}
        Index               postgres-logs
        Replace_Dots        On
        Generate_ID         On
        Suppress_Type_Name  On
        Include_Tag_Key     off
        Buffer_Size         1MB
        Retry_Limit         5
    # OUTPUT to Redis for redis logs
    [OUTPUT]
        Name                es
        Match               redis*
        Match_Regex         ^filename=redis.*$
        Host                ${elasticsearch_host}
        Port                ${elasticsearch_port}
        Index               redis-logs
        Replace_Dots        On
        Generate_ID         On
        Suppress_Type_Name  On
        Include_Tag_Key     off
        Buffer_Size         1MB
        Retry_Limit         5
    # OUTPUT kube-proxy logs
    [OUTPUT]
        Name                es
        Match               kube-proxy*
        Match_Regex         ^filename=kube-proxy.*$
        Host                ${elasticsearch_host}
        Port                ${elasticsearch_port}
        Index               kube-proxy-logs
        Replace_Dots        On
        Generate_ID         On
        Suppress_Type_Name  On
        Include_Tag_Key     off
        Buffer_Size         1MB
        Retry_Limit         5
    # #  Default OUTPUT for any other logs
    # [OUTPUT]
    #     Name                es
    #     Match               kubernetes.*
    #     Host                ${elasticsearch_host}
    #     Port                ${elasticsearch_port}
    #     Index               kubernetes-logs
    #     Replace_Dots        On
    #     Generate_ID         On
    #     Suppress_Type_Name  On
    #     Include_Tag_Key     off
    #     Buffer_Size         1MB
    #     Retry_Limit         5

    # [OUTPUT]
    #     Name            kafka
    #     Match           *
    #     Brokers         kafka-headless.logharbour.svc.cluster.local:9092
    #     Topic           fluent-bit-logs
    #     rd.key.format   none
    #     format          json_lines
    #     # Optional settings for better performance and reliability
    #     queue_full_behavior block
    #     retry_max        5
    #     retry_interval   1
  parsers.conf: |
    [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S %z
        Time_Keep           On
    [PARSER]
        Name                syslog
        Format              regex
        Regex               ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key            time
        Time_Format         %b %d %H:%M:%S
  extract_prefix.lua: |
    function extract_prefix(tag, timestamp, record)
      local pod_name, namespace, fname = nil, nil, nil
      local pattern = ".*/(.-)-(.-)-(.*)_(.*)_(.*).log"
      local filename = record["filename"]
      local match = string.match(filename, pattern)
      if match then
        pod_name = match[1]
        namespace = match[4]
        fname = match[5]
      end
      if filename ~= nil then
          -- Extract prefix before first underscore
          local prefix = string.match(filename, "^([^_]+)")
          if prefix ~= nil then
              record["filename"] = fname
              record["namespace"] = namespace
              record["pod_name"] = pod_name
          end
      end
      return 1, timestamp, record
    end
