# second-cluster.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    image: kindest/node:v1.32.2
    extraPortMappings:
      - containerPort: 80 # cluster port
        hostPort: 86   # host port 
        protocol: TCP # It's good practice to specify the protocol
      - containerPort: 443
        hostPort: 446
        protocol: TCP # It's good practice to specify the protocol
      - containerPort: 30020
        hostPort: 30020
        protocol: TCP
      - containerPort: 30021
        hostPort: 30021
        protocol: TCP
      - containerPort: 30022
        hostPort: 30022
        protocol: TCP
      - containerPort: 30023
        hostPort: 30023
        protocol: TCP
      - containerPort: 30024
        hostPort: 30024
        protocol: TCP
      - containerPort: 30025
        hostPort: 30025
        protocol: TCP
  - role: worker
    image: kindest/node:v1.32.2
  # - role: worker
  #   image: kindest/node:v1.32.2
