# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

networks:
  default:
    name: aniket-opentelemetry-demo
    driver: bridge

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command:
      - "--memory.max-traces=5000"
      - "--query.ui-config=/etc/jaeger/jaeger-ui.json"
      # - "--query.base-path=jaeger:16686"
      # - "--prometheus.query.normalize-calls=true"
      # - "--prometheus.query.normalize-duration=true"
    environment:
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - 4317
      - 4318
    deploy:
      resources:
        limits:
          memory: 400M
    logging: *logging

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.114.0
    container_name: otelcol
    deploy:
      resources:
        limits:
          memory: 200M
    command: ["--config=/conf/otel-collector.yaml"]
    privileged: true
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./otel-collector.yaml:/conf/otel-collector.yaml
    logging: *logging

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    #   - --web.console.templates=/etc/prometheus/consoles
    #   - --web.console.libraries=/etc/prometheus/console_libraries
    #   - --storage.tsdb.retention.time=1h
    #   - --config.file=/etc/prometheus/prometheus.yaml
    #   - --storage.tsdb.path=/prometheus
    #   - --web.enable-lifecycle
    #   - --web.route-prefix=/
    #   - --enable-feature=exemplar-storage
      # - --enable-feature=otlp-write-receiver
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    # restart: unless-stopped
    ports:
      - "9090:9090"
    logging: *logging    


  # Grafana : http://localhost:3000/grafana
  grafana:
    image: grafana/grafana:latest
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=grafana-opensearch-datasource"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    logging: *logging