global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: "otel-collector"
  #   static_configs:
  #     - targets: ["otel-collector:8889"]

  - job_name: "host-metrics"
    static_configs:
      - targets: ["host.docker.internal:8889"]

  - job_name: "external-otel-metrics"
    static_configs:
      - targets: ["host.docker.internal:8899"]